[project]
name = "metodos-numericos-gui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "biseccion",
    "descomposicion-lu",
    "gauss-seidel",
    "interpolacion-newton",
    "metodos-numericos-base",
    "newton-raphson",
    "punto-fijo",
    "regresion-lineal",
    "secante",
]

[project.scripts]
metodos-numericos = "metodos_numericos_gui:iniciar_gui"

[tool.uv.sources]
biseccion = { workspace = true }
descomposicion-lu = { workspace = true }
gauss-seidel = { workspace = true }
interpolacion-newton = { workspace = true }
metodos-numericos-base = { workspace = true }
newton-raphson = { workspace = true }
punto-fijo = { workspace = true }
regresion-lineal = { workspace = true }
secante = { workspace = true }

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
